name: Rust

on:
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Simple check
      run: cargo check --verbose
    - name: Check feature serde
      run: cargo check --features serde --verbose
    - name: Check feature metric
      run: cargo check --features metrics --verbose
    - name: Check feature optimizer
      run: cargo check --features optimizer --verbose
    - name: Check all
      run: cargo check --all-features --verbose
    
    - name: Install wasm32 target
      run: rustup target add wasm32-unknown-unknown
    
    - name: Check wasm
      run: cargo check --target=wasm32-unknown-unknown --verbose
    - name: Check wasm all
      run: cargo check --target=wasm32-unknown-unknown --all-features --verbose
    
    - name: Run tests
      run: cargo test --verbose
    - name: Run tests all
      run: cargo test --all-features --verbose
